/*
------------Old School Roleplay Project-------------------
------------Dibuat Oleh : *Nopaal19     ------------------
------------              *Dxl          ------------------
------------              *naslinathmar ------------------
------------              20 Juni 2023  ------------------
------------Dont Remove this Copyright! ------------------
*/
// Server Define
#define TEXT_GAMEMODE	"Oldschool v1"
#define TEXT_WEBURL		""
#define TEXT_LANGUAGE	"Bahasa Indonesia"
#define SERVER_NAME     "Old School Roleplay"

//Mysql Configuration
#define		MYSQL_HOST 			"localhost"
#define		MYSQL_USER 			"root"
#define		MYSQL_PASSWORD 		""
#define		MYSQL_DATABASE 		"oldschool"

//autokick at login system
#define		SECONDS_TO_LOGIN 	20

// default spawn point: Old School Yard
#define 	DEFAULT_POS_X       513.95
#define 	DEFAULT_POS_Y 		-2497.85
#define 	DEFAULT_POS_Z 		1.28
#define 	DEFAULT_POS_A 		180